version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=api.v2.coditeach.kz
      - LETSENCRYPT_HOST=api.v2.coditeach.kz