-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.classroom
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    code character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "managerId" uuid NOT NULL,
    CONSTRAINT "PK_729f896c8b7b96ddf10c341e6ff" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lesson
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    language character varying COLLATE pg_catalog."default" NOT NULL,
    grade integer NOT NULL,
    "chapterQueue" integer NOT NULL,
    chapter character varying COLLATE pg_catalog."default" NOT NULL,
    "topicTitle" character varying COLLATE pg_catalog."default" NOT NULL,
    "topicQueue" integer NOT NULL,
    "lessonType" character varying COLLATE pg_catalog."default" NOT NULL,
    "lessonObjectives" character varying COLLATE pg_catalog."default" NOT NULL,
    "lessonEquipment" character varying COLLATE pg_catalog."default",
    "lessonStart" character varying COLLATE pg_catalog."default" NOT NULL,
    "lessonMiddle" character varying COLLATE pg_catalog."default" NOT NULL,
    "lessonEnd" character varying COLLATE pg_catalog."default" NOT NULL,
    "linkForDoc" character varying COLLATE pg_catalog."default",
    "additionalResources" character varying COLLATE pg_catalog."default",
    "priorKnowledge" character varying COLLATE pg_catalog."default",
    "videoLinks" character varying COLLATE pg_catalog."default",
    "presentationLinks" character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_0ef25918f0237e68696dee455bd" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.manager
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    role character varying COLLATE pg_catalog."default" NOT NULL,
    "schoolId" uuid NOT NULL,
    profile_image character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_b3ac840005ee4ed76a7f1c51d01" PRIMARY KEY (id),
    CONSTRAINT "UQ_ee8fba4edb704ce2465753a2edd" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.manager_verification
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    "verificationCode" character varying COLLATE pg_catalog."default" NOT NULL,
    "isVerified" boolean NOT NULL,
    "updatedAt" timestamp without time zone NOT NULL,
    "limitCount" integer NOT NULL DEFAULT 1,
    CONSTRAINT "PK_4ad6193bc958200330b56e882bf" PRIMARY KEY (id),
    CONSTRAINT "UQ_0023639e3aff2b6bd49d2b70685" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.school
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    country character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_57836c3fe2f2c7734b20911755e" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.student
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "accountId" character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    "classroomId" uuid NOT NULL,
    profile_image character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY (id),
    CONSTRAINT "UQ_627399e684b01d45317af431237" UNIQUE ("accountId")
);

CREATE TABLE IF NOT EXISTS public.typeorm_metadata
(
    type character varying COLLATE pg_catalog."default" NOT NULL,
    database character varying COLLATE pg_catalog."default",
    schema character varying COLLATE pg_catalog."default",
    "table" character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    value text COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.classroom
    ADD CONSTRAINT "FK_8d5091e32efaa48ab70cfa2186c" FOREIGN KEY ("managerId")
    REFERENCES public.manager (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.manager
    ADD CONSTRAINT "FK_e7eb8023fb72b4a601c8883b8ee" FOREIGN KEY ("schoolId")
    REFERENCES public.school (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.student
    ADD CONSTRAINT "FK_426224f5597213259b1d58fc0f4" FOREIGN KEY ("classroomId")
    REFERENCES public.classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;